config/routes.rb
Rails.application.routes.draw do
  devise_for :specialists
  devise_for :clients, controllers: { omniauth_callbacks: 'clients/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :specialists, only: [ :index, :show ] do
    resources :treatments, only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :client
  belongs_to :treatment
  validates :location, presence: true
  validates :client, presence: true
  validates :treatment, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :subcategories, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :reviews

  mount_uploader :photo, PhotoUploader

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = Client.find_by(provider: auth.provider, uid: auth.uid)
    user ||= Client.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = Client.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :client
  belongs_to :specialist

  validates :title, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :client, presence: true
  validates :specialist, presence: true
end

app/models/specialist.rb
class Specialist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # mount_uploader :photo, PhotoUploader

  has_many :treatments
  has_many :subcategories, through: :treatments
  has_many :appointments, through: :treatments
  has_many :reviews
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :treatments
  has_many :specialists, through: :treatments
  validates :name, presence: true, uniqueness: true
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :specialist
  belongs_to :subcategory
  validates :description, presence: true, uniqueness: { case_sensitive: false, scope: :specialist, message: "You already have this treatment" }
  validates :price, presence: true, numericality: true
  validates :duration, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 5 }
  validates :specialist, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_specialist!
  before_action :authenticate_client!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/clients/omniauth_callbacks_controller.rb
class Clients::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    client = Client.find_for_facebook_oauth(request.env['omniauth.auth'])

    if client.persisted?
      sign_in_and_redirect client, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_client_registration_url
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_specialist!, only: :home
  skip_before_action :authenticate_client!, only: :home

  def home
  end
end

app/controllers/specialists_controller.rb
class SpecialistsController < ApplicationController
  skip_before_action :authenticate_specialist!, only: [:index, :show]
  skip_before_action :authenticate_client!, only: [:index, :show]

  def index
    @specialists = Specialist.eager_load(treatments: [:subcategory]).all
    if params[:price]
      params[:price][:min] = 0 if params[:price][:min] == ""
      params[:price][:max] = 1000 if params[:price][:max] == ""
      @specialists = @specialists.joins(:treatments).where("treatments.price BETWEEN ? AND ?", params[:price][:min], params[:price][:max]).uniq
    end

    if params[:subcategory]
      subcategory_id_array = Subcategory.where(name: params[:subcategory]).pluck(:id)
      @specialists = @specialists.where("treatments.subcategory_id IN (?)", subcategory_id_array)
    end

    if params[:rating]
      @specialists = @specialists.where(rating: params[:rating])
    end
  end

  def show
    @specialist = Specialist.find(params[:id])
  end

  private

  def search_params
  end
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
    skip_before_action :authenticate_specialist!, only: [:show]
  skip_before_action :authenticate_client!, only: [:show]

  def show
    @treatment = Treatment.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>HomeTreat | Get your treatment. Anytime. Anywhere.</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %><!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">


    <!-- <meta name="description" content="HomeTreat info's">
    <meta charset="utf-8" />
    <link rel="icon" href="" type="image/png" />
    <meta property="og:title" content="HomeTreat | USP" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="https://www.hometreat.nl/" />
    <meta property="og:image" content="" />
    <meta property="og:description" content="HomeTreat description" />
    <meta property="og:site_name" content="HomeTreat" />
    <link rel="alternate" hreflang="en" href="/" />
    <link rel="alternate" hreflang="nl" href="/nl" />
    <link rel="alternate" href="/" hreflang="x-default" />
    <link rel="canonical" href="https://www.hometreat.nl/" />
   -->
   </head>

  <body>
    <div style="min-height: calc(100vh - 70px)">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div style="padding-top: 50px;">
    <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    </div>
    <%= render 'shared/footer' %>

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>



  </body>

</html>

app/views/pages/home.html.erb
<%= video_tag "body.webm", :loop => true, :autoplay => true, poster: "ht_banner.jpg", class: "video" %>
<%= video_tag "body.mp4", :loop => true, :autoplay => true, poster: "ht_banner.jpg", class: "video" %>

<div class="videobanner" style="background-image: radial-gradient(rgba(201,74,1,0.4), rgba(201,74,1,0.3), rgba(1,104,201,0.5))">
  <div class="banner-content">
      <h1><span style="color: #FFFFFF">Home</span><span style="color: #0168c9">Treat</span></h1>
      <p><strong>Get your treatment</strong>. Anytime. Anywhere.</p>
      <%= render 'shared/searchbox' %>
  </div>
</div>

app/views/pages/home.html_BACKUP_27358.erb
<%= video_tag "body.webm", :loop => true, :autoplay => true, poster: "ht_banner.jpg", class: "video" %>
<%= video_tag "body.mp4", :loop => true, :autoplay => true, poster: "ht_banner.jpg", class: "video" %>

<div class="banner" style="background-image: radial-gradient(rgba(201,74,1,0.4), rgba(201,74,1,0.3), rgba(1,104,201,0.5))">
  <div class="banner-content">
      <h1><span style="color: #FFFFFF">Home</span><span style="color: #0168c9">Treat</span></h1>
      <p><strong>Get your treatment</strong>. Anytime. Anywhere.</p>
      <%= render 'shared/searchbox' %>
  </div>
</div>

app/views/pages/home.html_BASE_27358.erb
<%= video_tag "body.webm", :loop => true, :autoplay => true, poster: "ht_banner.jpg", class: "video" %>
<%= video_tag "body.mp4", :loop => true, :autoplay => true, poster: "ht_banner.jpg", class: "video" %>

<div class="banner" style="background-image: radial-gradient(rgba(201,74,1,0.5), rgba(201,74,1,0.3), rgba(1,104,201,0.9))">
  <div class="banner-content">
      <h1><span style="color: #FFFFFF">Home</span><span style="color: #0168c9">Treat</span></h1>
      <p><strong>Get your treatment</strong>. Anytime. Anywhere.</p>
      <%= link_to 'Book now', specialists_path, { class: 'btn btn-hometreat btn-lg' } %>
  </div>
</div>


 <!--  <video playsinline autoplay muted loop poster="" id="bgvid">
  <%= video_tag "hair.webm", :controls => true %>
  <%= video_tag "hair.mp4", :controls => true %>
  </video>


<video playsinline autoplay muted loop poster="" id="bgvid">
    <source src="public/hair.webm" type="video/webm">
    <source src="public/hair.mp4" type="video/mp4">
</video>

<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= asset_path "ht_banner.jpg" %>');">
  <div class="banner-content">
    <h1>HomeTreat</h1>
    <p>Get your treatment. Anytime. Anywhere.</p>
    <div class="container">
      <%= render 'shared/searchbox' %>
    </div>
  </div>
</div>
</div>


 -->

app/views/pages/home.html_LOCAL_27358.erb
<%= video_tag "body.webm", :loop => true, :autoplay => true, poster: "ht_banner.jpg", class: "video" %>
<%= video_tag "body.mp4", :loop => true, :autoplay => true, poster: "ht_banner.jpg", class: "video" %>

<div class="banner" style="background-image: radial-gradient(rgba(201,74,1,0.4), rgba(201,74,1,0.3), rgba(1,104,201,0.5))">
  <div class="banner-content">
      <h1><span style="color: #FFFFFF">Home</span><span style="color: #0168c9">Treat</span></h1>
      <p><strong>Get your treatment</strong>. Anytime. Anywhere.</p>
      <%= link_to 'Book now', specialists_path, { class: 'btn btn-hometreat btn-lg' } %>
  </div>
</div>

app/views/pages/home.html_REMOTE_27358.erb
<%= video_tag "body.webm", :loop => true, :autoplay => true, poster: "ht_banner.jpg", class: "video" %>
<%= video_tag "body.mp4", :loop => true, :autoplay => true, poster: "ht_banner.jpg", class: "video" %>

<div class="banner" style="background-image: radial-gradient(rgba(201,74,1,0.5), rgba(201,74,1,0.3), rgba(1,104,201,0.9))">
  <div class="banner-content">
      <h1><span style="color: #FFFFFF">Home</span><span style="color: #0168c9">Treat</span></h1>
      <p><strong>Get your treatment</strong>. Anytime. Anywhere.</p>
      <%= render 'shared/searchbox' %>
  </div>
</div>


 <!--  <video playsinline autoplay muted loop poster="" id="bgvid">
  <%= video_tag "hair.webm", :controls => true %>
  <%= video_tag "hair.mp4", :controls => true %>
  </video>


<video playsinline autoplay muted loop poster="" id="bgvid">
    <source src="public/hair.webm" type="video/webm">
    <source src="public/hair.mp4" type="video/mp4">
</video>

<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= asset_path "ht_banner.jpg" %>');">
  <div class="banner-content">
    <h1>HomeTreat</h1>
    <p>Get your treatment. Anytime. Anywhere.</p>
    <div class="container">
    </div>
  </div>
</div>
</div>


 -->

app/views/pages/show.html.erb
<!-- <div class="wrapper-blue">
  <div class="d-flex justify-content-center text-center">
    <h3>Your specialist</h3>
  </div>
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-6 col-sm-4">
          <div class ="card">
            <h3>Lilly</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus ea corporidignissimos.
            </p>
        </div>
        </div>
      </div>
    </div> -->


<!-- <div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/copenhagen');">
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2>Le Wagon Copenhagen</h2>
          <p>Very cool city, the best</p>
        </div>
        <img class="card-user avatar" src="https://kitt.lewagon.com/placeholder/users/atmosfeer">
        <a class="card-link" href="#" ></a>
      </div>
    </div>
  </div>
</div> -->




<!-- <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Le Wagon Shanghai</h2>
    <p>Very cool city, the best</p>
  </div>
  <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
  <a class="card-link" href="#" ></a>
</div> -->

app/views/shared/_card.html.erb
<!-- card partial, krijgt specialist instance mee -->
<div class="row">
  <div class="col-xs-12">
    <div class ="card">
      <div class="card-category"><%= specialist.first_name %></div>
      <div class="card-description">
        <p><%= truncate(specialist.bio, length: 60, escape: false) %></p>
      </div>
      <%= image_tag 'anne.jpg', class: "card-user avatar avatar-large" %>
      <div class="card-rating">

        <% if specialist.rating %>
          <% specialist.rating.times do %>
            <span class="fa fa-star checked"></span>
          <% end %>
          <% (5-specialist.rating).times do %>
            <span class="fa fa-star"></span>
          <% end %>
        <% else %>
          <p>no rating yet</p>
        <% end %>

        <ul>
          <% specialist.treatments.take(3).each do |tr| %>
            <li>
              <%= tr.subcategory.name %> - €
 <%= tr.price %>
            </li>
          <% end %>
        </ul>
      </div>
      <%= link_to "", specialist_path(specialist), class: "card-link" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © HomeTreat
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if client_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Client", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Specialist", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
           <% avatar_url = current_client.facebook_picture_url || "http://placehold.it/30x30" %>
           <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_client_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_client_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchbox.html.erb
<div class="searchbox">
  <!-- search query in url (bookmarken) -->
  <form method='GET' action="<%= specialists_path %>">
    <div class="form-group row">
      <!-- treatment types selection, meegegeven als array onder params[:subcategory] -->
      <label for="subcategory" class="col-sm-6 col-form-label">Please select</br></label>
      <div class="col-sm-6">
        <!-- <select multiple="multiple" class="custom-select mb-2 mr-sm-2 mb-sm-0" id="SubcategorySelect" name="sucategory[]"> -->

        <select class="selectpicker" name='subcategory[]' multiple>
          <option value="" disabled>Treatments</option>
          <% Category.all.each do |category| %>
            <optgroup label="<%= category.name %>">
              <% category.subcategories.each do |subcategory| %>
                <option value="<%= subcategory.name %>" ><%= subcategory.name %></option>
              <% end %>
            </optgroup>
          <% end %>
        </select>
      </div>
    </div>

    <!-- prijsrange, onder params[:price[:min ,:max]] -->
    <div class="form-group row">
      <label for="name" class="col-sm-3 col-form-label">price range:</label>
      <div class="col-sm-4">
        <input type="text" class="form-control" id="price_minimum" name="price[min]" placeholder="price in euro">
      </div>
      <div class="col-sm-1"> to </div>
      <div class="col-sm-4">
        <input type="text" class="form-control" id="price_maximum" name="price[max]" placeholder="price in euro">
      </div>
    </div>

    <!-- sterren, onder params[:rating[:1star, etc]] -->
    <div class="form-group row">
      <div class="col-sm-2">rating</div>
      <div class="col-sm-10">
        <div class="form-check">
          <label class="form-check-label">
            <input class="form-check-input rating-input" type="checkbox" name="rating[]" value="1"> 1 star
          </label>
          <label class="form-check-label">
            <input class="form-check-input rating-input" type="checkbox" name="rating[]" value="2"> 2 stars
          </label>
          <label class="form-check-label">
            <input class="form-check-input rating-input" type="checkbox" name="rating[]" value="3"> 3 stars
          </label>
          <label class="form-check-label">
            <input class="form-check-input rating-input" type="checkbox" name="rating[]" value="4"> 4 stars
          </label>
          <label class="form-check-label">
            <input class="form-check-input rating-input" type="checkbox" name="rating[]" value="5"> 5 stars
          </label>
        </div>
      </div>
    </div>

    <!-- location, onder params[:location[:lat, :lng]] -->
    <div class="form-group row">
      <label for="name" class="col-sm-2 col-form-label">Location:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="location_input" name="location" placeholder="eg. Overhoeksplein 2">
      </div>
    </div>

    <!-- searchknop, oerlelijk, anneke? -->
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary" id="search-button">Search</button>
      </div>
    </div>

  </form>
</div>

app/views/shared/_show.html.erb
<div class="wrapper-orange">
  <div class="text-center">
    <p>Your selected specialist<p>
  </div>
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-6 col-sm-4">
          <div class ="card">
            <div class="card-category">Hair Specialist</div>
              <div class="card-description">
                <h2>Lilly</h2>
                <p>I cut hair.</p>
              </div>
              <img class="card-user avatar" src="https://kitt.lewagon.com/placeholder/users/annekeweerts">
              <a class="card-link" href="#" ></a>
              <div class="card-rating">
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


<!-- <div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/copenhagen');">
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2>Le Wagon Copenhagen</h2>
          <p>Very cool city, the best</p>
        </div>
        <img class="card-user avatar" src="https://kitt.lewagon.com/placeholder/users/atmosfeer">
        <a class="card-link" href="#" ></a>
      </div>
    </div>
  </div>
</div> -->




<!-- <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Le Wagon Shanghai</h2>
    <p>Very cool city, the best</p>
  </div>
  <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
  <a class="card-link" href="#" ></a>
</div> -->

app/views/specialists/_specialist_treatments.html.erb
<div class="treatments_wrapper">
  <div class="treatments_title"><strong>Treatments offered by <%= @specialist.first_name %> <%= @specialist.last_name %></strong></div>
  <p></p>
  <div class="treatment-header">
   <div class="treatment-header-item item-width"><strong>Description</strong></div>
   <div class="treatment-header-item item-width"><strong>Duration</strong></div>
   <div class="treatment-header-item item-width"><strong>Price</strong></div>
   <div class="treatment-header-item item-width"><strong></strong></div>

  </div>
<% @specialist.treatments.each do |treatment| %>
<div class="treatment-data">

   <div class="treatment-item item-width">
    <%= treatment.description %> treatment
  </div>
  <div class="treatment-item item-width">
    <%= treatment.duration %> min
  </div>
  <div class="treatment-item item-width">
    € <%= treatment.price %>
  </div>
  <div class="treatment-item item-width">
    <a class = 'btn-treatment' href="<%= specialist_treatment_path(@specialist)%>">Select</a>
  </div>


</div>
<% end %>
</div>

app/views/specialists/booking.html.erb
test

app/views/specialists/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/treatments/show.html.erb
<h2>
  Please confirm your booking for <%= @treatment.description %> by <%= @treatment.specialist.first_name %> <%= @treatment.specialist.last_name %>
</h2>